[package]
name = "qt"
version = "0.1.0"
edition = "2021"

[dependencies]
qdrant-client = "1.11.2"
tokio = { version = "1.40.0", features = ["full", "rt-multi-thread"] }
prettytable = "0.10.0"
serde_json = "1.0.128"
